default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["DATABASE_USER"] || "root" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "password" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>

development:
  <<: *default
  database: labokun_development

test:
  <<: *default
  database: labokun_development

production:
  <<: *default
  database: labokun_production
